In [147]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
import optuna
from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error
)
plt.style.use('ggplot')

In [148]:
path = '../data/dataset/dataset.csv'
# path = '../data/processed_data/daily_average_all.csv'
data = pd.read_csv(path)
data.head()

,date,pm,location,temp,dew_point,humidity,pressure,wind_speed,precipitation,wind_dir_sin,wind_dir_cos,month,month_sin,month_cos
0,2023-01-01,104.875000,DN,23.5,16.9,68,1015.4,7.1,0.0,0.017452,0.999848,1,0.5,0.866025
1,2023-01-01,79.625000,BN,23.7,16.1,65,1015.3,6.7,0.0,0.707107,0.707107,1,0.5,0.866025
2,2023-01-01,79.375000,KPS,22.9,16.1,68,1015.6,7.2,0.0,0.325568,0.945519,1,0.5,0.866025
3,2023-01-02,90.583333,DN,24.0,17.4,69,1015.7,6.4,0.0,0.156434,0.987688,1,0.5,0.866025
4,2023-01-02,89.500000,BN,24.2,17.9,69,1015.6,5.3,0.0,0.642788,0.766044,1,0.5,0.866025

In [149]:
# data['date'] = pd.to_datetime(data['date'])
# data['month'] = data['date'].dt.month

def get_season(month):
    if month in [3, 4, 5]:
        return 'hot'
    elif month in [9, 10, 11]:
        return 'rain'
    elif month in [12, 1, 2]:
        return 'winter'

data['season'] = data['month'].apply(get_season)

data_encoded = pd.get_dummies(data, columns=['location', 'season'], drop_first=False)
data_encoded['original_location'] = data['location']
data_encoded = data_encoded.sort_values(by=['original_location', 'date']).reset_index(drop=True)
# data_encoded = data_encoded.drop(columns=['Unnamed: 0','index'])

data_encoded.head()

,date,pm,temp,dew_point,humidity,pressure,wind_speed,precipitation,wind_dir_sin,wind_dir_cos,month,month_sin,month_cos,location_BN,location_DN,location_KPS,season_hot,season_rain,season_winter,original_location
0,2023-01-01,79.625000,23.7,16.1,65,1015.3,6.7,0.0,0.707107,0.707107,1,0.5,0.866025,True,False,False,False,False,True,BN
1,2023-01-02,89.500000,24.2,17.9,69,1015.6,5.3,0.0,0.642788,0.766044,1,0.5,0.866025,True,False,False,False,False,True,BN
2,2023-01-03,110.500000,25.6,18.9,68,1014.7,6.1,0.0,0.515038,0.857167,1,0.5,0.866025,True,False,False,False,False,True,BN
3,2023-01-04,97.166667,26.5,19.1,65,1014.1,5.9,0.0,0.707107,0.707107,1,0.5,0.866025,True,False,False,False,False,True,BN
4,2023-01-05,95.583333,26.1,19.0,66,1013.7,6.3,0.0,0.681998,0.731354,1,0.5,0.866025,True,False,False,False,False,True,BN

In [150]:
def create_sliding_window(X, y, window_size=7):
    X_out, y_out = [], []
    for i in range(len(X) - window_size):
        window = X[i:i + window_size]
        X_out.append(window.flatten())
        y_out.append(y[i + window_size])
    return np.array(X_out), np.array(y_out)

window_size = 7

X_train_list, y_train_list = [], []
X_val_list, y_val_list = [], []
X_test_list, y_test_list = [], []

for loc in data_encoded['original_location'].unique():
    
    df_loc = data_encoded[data_encoded['original_location'] == loc].copy()
    
    X_loc = df_loc.drop(columns=["date", "month", "original_location"
                                 ,"precipitation","humidity","wind_speed","location_DN","location_KPS","location_BN"]).values
    y_loc = df_loc["pm"].values
    
    X_seq, y_seq = create_sliding_window(X_loc, y_loc, window_size)
    
    n = len(X_seq)
    train_end = int(n * 0.8)
    val_end   = int(n * 0.9)
    
    X_train_list.append(X_seq[:train_end])
    y_train_list.append(y_seq[:train_end])
    
    X_val_list.append(X_seq[train_end:val_end])
    y_val_list.append(y_seq[train_end:val_end])
    
    X_test_list.append(X_seq[val_end:])
    y_test_list.append(y_seq[val_end:])

X_train = np.vstack(X_train_list)
y_train = np.concatenate(y_train_list)

X_val = np.vstack(X_val_list)
y_val = np.concatenate(y_val_list)

X_test = np.vstack(X_test_list)
y_test = np.concatenate(y_test_list)

print("Train shape:", X_train.shape, y_train.shape)
print("Val shape:", X_val.shape, y_val.shape)
print("Test shape:", X_test.shape, y_test.shape)

Train shape: (2613, 77) (2613,)
Val shape: (327, 77) (327,)
Test shape: (327, 77) (327,)

In [151]:
def objective(trial):

    n_estimators = trial.suggest_int("n_estimators", 100, 500)
    max_depth = trial.suggest_int("max_depth", 3, 20)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 5)
    max_features = trial.suggest_categorical(
        "max_features", ["sqrt", "log2", None]
    )

    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)

    rmse = np.sqrt(mean_squared_error(y_val, y_pred))

    return rmse

In [152]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)
print("Best RMSE:", study.best_value)
print("Best params:", study.best_params)

[I 2026-02-17 04:16:53,050] A new study created in memory with name: no-name-c9ab4413-a187-4eff-abd6-d7d48b490e20
[I 2026-02-17 04:16:53,647] Trial 0 finished with value: 10.104333632786261 and parameters: {'n_estimators': 117, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:16:54,446] Trial 1 finished with value: 10.361573782254396 and parameters: {'n_estimators': 178, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:16:55,818] Trial 2 finished with value: 10.257728445907864 and parameters: {'n_estimators': 291, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:16:56,178] Trial 3 finished with value: 12.03675967653902 and parameters: {'n_estimators': 184, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:16:56,520] Trial 4 finished with value: 11.757687527719415 and parameters: {'n_estimators': 165, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:16:58,042] Trial 5 finished with value: 10.154932000014309 and parameters: {'n_estimators': 235, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:00,546] Trial 6 finished with value: 10.176327849546245 and parameters: {'n_estimators': 381, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:01,039] Trial 7 finished with value: 12.365449898976875 and parameters: {'n_estimators': 361, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:03,823] Trial 8 finished with value: 10.166405765225225 and parameters: {'n_estimators': 360, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:04,432] Trial 9 finished with value: 11.79820746695293 and parameters: {'n_estimators': 376, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:05,142] Trial 10 finished with value: 12.143166624265618 and parameters: {'n_estimators': 495, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:05,939] Trial 11 finished with value: 10.127377047491507 and parameters: {'n_estimators': 119, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:06,172] Trial 12 finished with value: 11.382844224010741 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:06,934] Trial 13 finished with value: 10.137361493510037 and parameters: {'n_estimators': 105, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:08,365] Trial 14 finished with value: 10.137341075049198 and parameters: {'n_estimators': 253, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:09,454] Trial 15 finished with value: 10.165131525565481 and parameters: {'n_estimators': 142, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:09,810] Trial 16 finished with value: 11.570646247234944 and parameters: {'n_estimators': 222, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:10,152] Trial 17 finished with value: 11.223914960791982 and parameters: {'n_estimators': 136, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 10.104333632786261.
[I 2026-02-17 04:17:13,138] Trial 18 finished with value: 10.057575204622271 and parameters: {'n_estimators': 486, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:13,855] Trial 19 finished with value: 11.646765559719555 and parameters: {'n_estimators': 478, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:16,002] Trial 20 finished with value: 10.09182930746797 and parameters: {'n_estimators': 310, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:18,964] Trial 21 finished with value: 10.08878378418719 and parameters: {'n_estimators': 445, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:21,727] Trial 22 finished with value: 10.095568698389723 and parameters: {'n_estimators': 434, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:24,697] Trial 23 finished with value: 10.086439103314133 and parameters: {'n_estimators': 441, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:28,078] Trial 24 finished with value: 10.113591605725052 and parameters: {'n_estimators': 444, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:31,084] Trial 25 finished with value: 10.09043618083679 and parameters: {'n_estimators': 425, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:35,011] Trial 26 finished with value: 10.128171900499062 and parameters: {'n_estimators': 466, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:35,894] Trial 27 finished with value: 11.44627116938933 and parameters: {'n_estimators': 414, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:36,659] Trial 28 finished with value: 11.977169074324125 and parameters: {'n_estimators': 401, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:39,972] Trial 29 finished with value: 10.11545465329687 and parameters: {'n_estimators': 464, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:42,018] Trial 30 finished with value: 10.062291420614363 and parameters: {'n_estimators': 335, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 18 with value: 10.057575204622271.
[I 2026-02-17 04:17:43,974] Trial 31 finished with value: 10.054788763962911 and parameters: {'n_estimators': 326, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:45,849] Trial 32 finished with value: 10.060833062640684 and parameters: {'n_estimators': 323, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:47,765] Trial 33 finished with value: 10.06217906205402 and parameters: {'n_estimators': 322, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:48,901] Trial 34 finished with value: 10.222394054129726 and parameters: {'n_estimators': 284, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:50,648] Trial 35 finished with value: 10.073835923068637 and parameters: {'n_estimators': 320, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:52,216] Trial 36 finished with value: 10.10586176292716 and parameters: {'n_estimators': 266, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:52,761] Trial 37 finished with value: 12.409426074157627 and parameters: {'n_estimators': 343, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:54,173] Trial 38 finished with value: 10.110179952569139 and parameters: {'n_estimators': 218, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:55,788] Trial 39 finished with value: 10.092281052324521 and parameters: {'n_estimators': 280, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:56,365] Trial 40 finished with value: 12.485305873958113 and parameters: {'n_estimators': 397, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:17:58,226] Trial 41 finished with value: 10.060069665542052 and parameters: {'n_estimators': 331, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:00,041] Trial 42 finished with value: 10.06266775611693 and parameters: {'n_estimators': 306, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:02,501] Trial 43 finished with value: 10.059884878252802 and parameters: {'n_estimators': 344, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:05,054] Trial 44 finished with value: 10.060428346389566 and parameters: {'n_estimators': 354, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:07,743] Trial 45 finished with value: 10.060998193030798 and parameters: {'n_estimators': 357, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:10,470] Trial 46 finished with value: 10.08351656034911 and parameters: {'n_estimators': 386, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:13,401] Trial 47 finished with value: 10.09276870244525 and parameters: {'n_estimators': 369, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:14,181] Trial 48 finished with value: 11.451223454361326 and parameters: {'n_estimators': 348, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 31 with value: 10.054788763962911.
[I 2026-02-17 04:18:14,633] Trial 49 finished with value: 11.916351580056821 and parameters: {'n_estimators': 238, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 31 with value: 10.054788763962911.

Best RMSE: 10.054788763962911
Best params: {'n_estimators': 326, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None}

In [153]:
X_trainval = np.vstack((X_train, X_val))
y_trainval = np.concatenate((y_train, y_val))

best_params = study.best_params

best_rf = RandomForestRegressor(
    **best_params,
    random_state=42,
    n_jobs=-1
)

best_rf.fit(X_trainval, y_trainval)

RandomForestRegressor(max_depth=10, max_features=None, min_samples_leaf=5,
                      min_samples_split=8, n_estimators=326, n_jobs=-1,
                      random_state=42)

In [154]:
def mean_bias_error(y_true, y_pred):
    return np.mean(y_pred - y_true)

In [155]:
y_pred = best_rf.predict(X_test)

In [156]:
r2   = r2_score(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
mbe  = mean_bias_error(y_test, y_pred)

print("===== Test Metrics =====")
print(f"R2   : {r2:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MBE  : {mbe:.4f}")

===== Test Metrics =====
R2   : 0.4926
MSE  : 170.3517
MAE  : 10.1995
RMSE : 13.0519
MBE  : 3.5374