In [116]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [117]:
pm = 'rawdata/dn_pm.csv'
weather = 'rawdata/dn_weather.csv'
location = 'DN'
pm_data = pd.read_csv(pm)
weather_data = pd.read_csv(weather)

In [118]:
pm_data.head()

               time  us_aqi_pm2_5 (USAQI)
0  2023-01-01T00:00                   108
1  2023-01-01T01:00                   109
2  2023-01-01T02:00                   110
3  2023-01-01T03:00                   111
4  2023-01-01T04:00                   112

In [119]:
weather_data.head()

,date,temperature_2m_mean,dew_point_2m_mean,relative_humidity_2m_mean,pressure_msl_mean,wind_speed_10m_mean,winddirection_10m_dominant,precipitation_sum
0,1/1/2023,23.5,16.9,68,1015.4,7.1,1,0.0
1,1/2/2023,24.0,17.4,69,1015.7,6.4,9,0.0
2,1/3/2023,25.0,19.1,71,1015.1,5.9,355,0.0
3,1/4/2023,26.7,18.8,63,1014.3,7.3,8,0.0
4,1/5/2023,26.0,19.2,68,1013.9,6.6,13,0.0

In [120]:
pm_data['time'] = pd.to_datetime(pm_data['time'])
daily_avg = (
    pm_data
    .set_index('time')  
    .resample('D')       
    .mean()        
    .reset_index()    
)
daily_avg = daily_avg.rename(columns={
    'time': 'date',
    'us_aqi_pm2_5 (USAQI)': 'pm'
})
daily_avg["location"] = location
daily_avg = daily_avg.reset_index()
daily_avg.head()

   index       date          pm location
0      0 2023-01-01  104.875000       DN
1      1 2023-01-02   90.583333       DN
2      2 2023-01-03  115.958333       DN
3      3 2023-01-04   83.875000       DN
4      4 2023-01-05   84.125000       DN

In [121]:
weather_data['date']= pd.to_datetime(weather_data['date'])
weather_data = weather_data.rename(columns={
    'temperature_2m_mean': 'temp',
    'dew_point_2m_mean': 'dew_point',
    'relative_humidity_2m_mean': 'humidity',
    'pressure_msl_mean': 'pressure',
    'wind_speed_10m_mean': 'wind_speed',
    'winddirection_10m_dominant': 'wind_direction',
    'precipitation_sum': 'precipitation'
})
weather_data.head()

,date,temp,dew_point,humidity,pressure,wind_speed,wind_direction,precipitation
0,2023-01-01,23.5,16.9,68,1015.4,7.1,1,0.0
1,2023-01-02,24.0,17.4,69,1015.7,6.4,9,0.0
2,2023-01-03,25.0,19.1,71,1015.1,5.9,355,0.0
3,2023-01-04,26.7,18.8,63,1014.3,7.3,8,0.0
4,2023-01-05,26.0,19.2,68,1013.9,6.6,13,0.0

In [122]:
print(daily_avg.shape, weather_data.shape)

(1096, 4) (1096, 8)

In [123]:
merged_df = pd.merge(
    daily_avg,
    weather_data,
    on='date',          # key ที่ใช้เชื่อม
    how='inner'         # เอาเฉพาะวันที่ตรงกัน
)

merged_df.head()

,index,date,pm,location,temp,dew_point,humidity,pressure,wind_speed,wind_direction,precipitation
0,0,2023-01-01,104.875000,DN,23.5,16.9,68,1015.4,7.1,1,0.0
1,1,2023-01-02,90.583333,DN,24.0,17.4,69,1015.7,6.4,9,0.0
2,2,2023-01-03,115.958333,DN,25.0,19.1,71,1015.1,5.9,355,0.0
3,3,2023-01-04,83.875000,DN,26.7,18.8,63,1014.3,7.3,8,0.0
4,4,2023-01-05,84.125000,DN,26.0,19.2,68,1013.9,6.6,13,0.0

In [124]:
print(merged_df.shape)

(1096, 11)

In [125]:
merged_df.to_csv('processed_data/daily_average'+location+'.csv')
print("Data saved successfully!")

Data saved successfully!